### ISSUE TITLE
Large number of missing localization errors in error.log

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#16]
Loading BP into CK3 (after stripping the history/character file, which causes a crash if included [not unexpected]), there are around 30k lines of errors. Some of these have to do with Issue #15 but others seem to have to do with localizations not existing. 

Biggest reason this is a problem (on my end at least) is it makes it difficult to parse the error log to track down implementation bugs in other parts we're working on simultaneously (e.g., the Henotikon and such).

Most notable errors seem to be:
* No Vlach culture for some decisions
* Error on 00_cultural_maa_innovations.txt:44 (missing Vlach culture)
* Dynasties having no scripted source cultures
*  Dynasties not having founders for COA generation
* Coat of Arm Color Lists throwing errors (?)
* missing localizations for many cultures (e.g. [22:15:39][culture_names.cpp:98]: Missing loc for name 'Ostrogotho' in culture 'gepid')
* Unexpected tokens in BP_dynasties.txt

@AvalonXD I think you created most of these culture files and are thus in the best position to direct how to start plugging these up, either by yourself or assigning sub-parts of this to other people if it's a lot of work to fix. If you can narrow down which parts specifically are causing problems, I can attempt batch fixes for some of these errors that are large and repetitive.

Attached is the log file I generated today so you can see for yourself.

[error.log](https://github.com/loup99/BP/files/5759728/error.log)

**Comment by AvalonXD** [comment]
Aside from Latin and associated group cultures (which Loup said he wanted to do) most of these are either not culture issues, already fixed or things which are outside general culture implementation. What I generally do when searching errors is search for close to what I think the error may be (i.e. if it's an event in eventFile1.txt I search for eventFile1), mass deletion of unassociated issues or usually the error is the last thing in the error log anyway.

I could attach my temp Latin culture list until Loup is finished with the real one to at least squash the Vlach errors etc?

**Comment by LT-Rascek** [comment]
That'd be helpful for debugging my own code. Sounds like PR #13 has quashed most of these already so it shouldn't be problem.

**Comment by AvalonXD** [comment]
[00_latin.txt](https://github.com/loup99/BP/files/5760606/00_latin.txt) and the culture names file as a .txt you'd have to change to .yml
[BP_cultures_l_english.txt](https://github.com/loup99/BP/files/5760644/BP_cultures_l_english.txt)

**Comment by LT-Rascek** [comment]
Thanks @AvalonXD ; since this is more-or-less already handled, I'll close this issue.
