### ISSUE TITLE
Fix missing localizations/breaks in Faith GUI windows

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#17]
1.2.2 patch broke some localizations and layout aspects associated with the custom faith creation GUI (which we require because of custom Christian doctrines) and now seems to have some other potential errors. Fix these issues.

Note: This doesn't seem to really break anything from the player perspective from what I tested, but we should prune these errors when we get the chance.

@loup99 : I can't assign this to myself, so if you could do that for me.

**Comment by AvalonXD** [comment]
I've fixed this already. It's in my latest PR #13

**Comment by LT-Rascek** [comment]
Roger. Closing.
