### ISSUE TITLE
Implement Missing Cultures and Religion Aspects

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#21]
Religion:
* Overhaul event widgets to support scrolling options for hellenic patron deity mechanic.
* Localization for new Buddhist religions

Cultures:
*  Get basic localization for mzab-* and balto-urgic cultures.

Beta features:
* Implement monument building decision akin to runestone raising for monument builder tenet. Probably has to be tied to runestone raising event and DLC FP1.

**Comment by loup99** [comment]
In addition to Nuristani, Udmurt and Kalash seem to be missing names.

**Comment by LT-Rascek** [comment]
> In addition to Nuristani, Udmurt and Kalash seem to be missing names.

Updated opening post, thank you.

**Comment by loup99** [comment]
The new Latin cultures still need name fixes as well.

**Comment by LT-Rascek** [comment]
Migrated remaining tasks to other issues.
