### ISSUE TITLE
476 BM CTD

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#28]
Along with #27, I've started trying to fix the 476 Bookmark CTD.

Doing some investigation, I made a second 475 bookmark with a single character (Julius Nepos) owning k_croatia and renumbering him to some very high number (900000 as per ck3 wiki suggestion). That managed, however slowly, to **not** CTD. So some character id collision might be playing a roll, but I doubt it's the single cause.

I've got some very coarse work started locally on rewriting the title history but I'm still getting CTD with full character history _after_ removing all CK3 vanilla characters and reimporting the character history data. I'll probably back up and spend some time with sed on the character history files to cut down on the number of errors associated with it in error.log (stuff like "invalid traits" and incorrect education trait mapping should be a quick fix).

**Comment by AvalonXD** [comment]
The CTD is caused by the Irish and Sardinian history files. If you change them both to Irish1 and Sardinian1 or outright delete them you'll be able to access the bookmark.

**Comment by LT-Rascek** [comment]
@AvalonXD: That fixed it.
