### ISSUE TITLE
Map/History Discussion

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#30]
Some questions I have on mapping landed titles &c. meant to stimulate discussion

* @loup99 : I noticed that many of the duchies/kingdoms in former Roman lands mapped to Diocletian's 395 reorganization of the Empire. Do we want to extend that pattern for BP and add all them in as I did on #27, or instead map WtWSMS directly with minimal tweaks. Alternatively, we can probably add some bits to the gui to make it possible for non-bureaucratic/subroman states to shatter the roman governance in the region (producing the sort of _de jure_ duchies you'd see arise later).
* While much of Western Europe and India is mappable from CK2 to CK3 in one form or another, this doesn't really hold for other parts. In particular, North Africa is a mess (part of the trouble is inconsistent transliteration from Berber/Arabic, but even so there's a lot that is not mapped correctly or maps to empty space on the CK3 map). How do we want to approach this?
* Are Altava, Ourasenis, Hodna, Aures, Capsus, and Dorsale successor states to the Mauro-Roman Kingdom (as in, they came into being in the late 500s) or are my sources on those kingdoms incorrect and they **_are_** extant in 476?
* Do we want to create a "nomad" government that is a carbon-copy of tribal to make future conversion easier when Paradox gets around to implementing nomadic governments.
* Large portions of the CK3 map are brand new and thoroughly tribal, like Northern Asia/Tibet. How do we want to handle adding characters for this so we're not spammed with error notes about empty province history? I can probably implement some script to generate that sort of tribal history for us, but I'd really need to format the province history files in those regions to make it less of a pain to code. I'm thinking following the pattern laid out in the Horn of Africa Tribal duchies taken from the _Periplus of the Erythraean Sea_ with those specific dates (420 &c.) listed for the characters in WTWSMS.

Aside: I've been doing more work on landed titles [here](https://github.com/LT-Rascek/BP/tree/merged_test_environment), primarily mapping county data to the CK3 map. Because of the nature of Paradox's file formats, it should be very easy to port specific changes to main if people agree with the proposals. Besides a handful of additional characters in _lt_rascek_new_chars.txt, the only changes to characters in the files are fixing some mismatched religion/cultures that annoyed me; I have no problems obliterating those changes to bring Abian36's new history as those culture/religion changes were a done with a simple bash script.

79cab07 covers the easiest portions of the map (former West Roman Empire (sans Britain), North Africa, East Africa, Arabia, and the Persian Empire) and moving forward will end up being the less well-attested portions in Germania et al.

**Comment by loup99** [comment]
> @loup99 : I noticed that many of the duchies/kingdoms in former Roman lands mapped to Diocletian's 395 reorganization of the Empire. Do we want to extend that pattern for BP and add all them in as I did on #27, or instead map WtWSMS directly with minimal tweaks. Alternatively, we can probably add some bits to the gui to make it possible for non-bureaucratic/subroman states to shatter the roman governance in the region (producing the sort of de jure duchies you'd see arise later).

The de jure in CK2 is the one of 395 (Diocletian was long dead by then, but his reorganisation is the main institutional framework basis yes) plus modifications for balance and adaptation for CK2 mechanics. For example, we do not include the praetorian prefectures above the dioceses, while the oversized dioceses are divided in several smaller ones.

> While much of Western Europe and India is mappable from CK2 to CK3 in one form or another, this doesn't really hold for other parts. In particular, North Africa is a mess (part of the trouble is inconsistent transliteration from Berber/Arabic, but even so there's a lot that is not mapped correctly or maps to empty space on the CK3 map). How do we want to approach this?

Do you mean specifically for the sub-Saharan and Saharan parts of the map? We want to keep the existing tribes, the Garamantes for example were major players in this area even if they were on the decline.

> Are Altava, Ourasenis, Hodna, Aures, Capsus, and Dorsale successor states to the Mauro-Roman Kingdom (as in, they came into being in the late 500s) or are my sources on those kingdoms incorrect and they are extant in 476?

What sources are you talking of? They are meant to be present in 476 on the map.

> Do we want to create a "nomad" government that is a carbon-copy of tribal to make future conversion easier when Paradox gets around to implementing nomadic governments.

Maybe, but this shouldn't be the priority in my opinion since we already have a nomad/tribal divide in store from CK2.

> Large portions of the CK3 map are brand new and thoroughly tribal, like Northern Asia/Tibet. How do we want to handle adding characters for this so we're not spammed with error notes about empty province history? I can probably implement some script to generate that sort of tribal history for us, but I'd really need to format the province history files in those regions to make it less of a pain to code. I'm thinking following the pattern laid out in the Horn of Africa Tribal duchies taken from the Periplus of the Erythraean Sea with those specific dates (420 &c.) listed for the characters in WTWSMS.

Characters in those areas would be fictional anyway, so that is the usual procedure of taking dynasty names and names from our lists to create characters.

**Comment by loup99** [comment]
On the Romano-Berber kingdoms:

![image](https://user-images.githubusercontent.com/7620180/114685351-114a8280-9d12-11eb-9c39-0dfb3152e0f8.png)

Source: figure 4.2 from the book _Vandals, Romans and Berbers: New Perspectives on Late Antique North Africa_ by A.H. Merrills. Originally it is from Christian Curtois' _Les Vandales et l'Afrique_, p. 334. It depicts the eight Christianized Romano-Berber states during the sixth century.

**Comment by LT-Rascek** [comment]
> The de jure in CK2 is the one of 395 (Diocletian was long dead by then, but his reorganisation is the main institutional framework basis yes) plus modifications for balance and adaptation for CK2 mechanics. For example, we do not include the praetorian prefectures above the dioceses, while the oversized dioceses are divided in several smaller ones.

So this is my proposal in the code for Roman Kingdoms:
![e_rome_kingdoms](https://user-images.githubusercontent.com/55886300/114736943-8c149d00-9d14-11eb-9f99-5f26806bdfee.png)

And for Duchies:
![e_rome_duchies](https://user-images.githubusercontent.com/55886300/114736985-96369b80-9d14-11eb-9129-58647fcf9bba.png)

This aligns it with the 395 imperial reorganization by Diocleatian. The general gist is kingdom = diocese and duchy = province. I presume the Hispanic diocese is too large and should be subdivided so that the provinces become kingdoms instead, along with breaking up Roman Africa into the kingdoms of Maghreb, Africa, and Tripoltania?

Looking at Abian36's British changes, he made 3 kingdoms: Britannia Prima, Britannia Secunda, Angleterre. I've maintained k_england as a single kingdom and divided it into 5 duchies: Valentia (Wales), Brittania Secunda (York), Flavia Caesarensis (Linconshire), Maxima Caesarensis (London), and Britannia Prima (Cornwall). Do you want to import Abian36's titles or stick with the 395 titles?

As an aside, we (should) be able to manipulate the can_create conditions to prevent non-Subroman/bureaucratic governments from creating these roman titles and instead giving them the option of "shattering" the Roman Administraiton and replacing it with new, smaller duchies that match the CK3 de jure setup. That'd make it possible to support both the Roman province system while still allowing for the general degradation of Roman governance that comes with the barbarian invasions.

> Do you mean specifically for the sub-Saharan and Saharan parts of the map? We want to keep the existing tribes, the Garamantes for example were major players in this area even if they were on the decline.

Yes; while k_garmantes will sit on Ghat, Germa, Muzruk, Zawila, the minor Garamantes principalities really don't have their own territory or would be subordinate to k_garamantes. It's primarily a space issue and, with a few exceptions, I can't match locations (example, c_taxseft or c_refrus) to positions on the CK3 map.

> What sources are you talking of? They are meant to be present in 476 on the map.

The Romano-Moor Kingdom (listed [here](https://upload.wikimedia.org/wikipedia/commons/2/2b/East-Hem_500ad.jpg) and the wiki [here](https://en.wikipedia.org/wiki/Mauro-Roman_Kingdom), which notes a description from [_History of the Wars_](https://en.wikisource.org/wiki/History_of_the_Wars/Book_IV#X) by Procopius. Altava, Ourasensis, et al appear to be successor states to the Roman-Moor Kingdom. His description states the Roman-Moor kingdom stretching from c_tangiers to c_tanas, which overlaps much of Roman-Moor Kingdoms.

Currently in that commit I've remapped those kingdoms I could fit on the map (Altava, Ouarsensis, Sicca Veneria, Cabon, and Capsa) but there is not enough room for all of them from mapping directly from CK2. On the other hand, some counties like Hodna are listed as part of another kingdom but instead should be part of an independent polity (in that case, Hodna should be part of k_hodna, not k_sicca_veneria).

> Maybe, but this shouldn't be the priority in my opinion since we already have a nomad/tribal divide in store from CK2.

Right; in essence, nomad would just be an alias for tribal to line up for later replacement. I think it'd save work down the line.

> Characters in those areas would be fictional anyway, so that is the usual procedure of taking dynasty names and names from our lists to create characters.

Roger; I'll see about automating that to save the effort.

=====
Here's some maps for reference; so far I've done the empires of Perisa, Arabia, Africa, Byzantium, Rome, Hispaniae, and Gaul, and am making headway in Germania Magna:
Empire Titles:
![Empires](https://user-images.githubusercontent.com/55886300/114741155-7d2fe980-9d18-11eb-9a0c-68545d2f3fb0.png)

Kingdoms:
![Kingdoms](https://user-images.githubusercontent.com/55886300/114741202-8751e800-9d18-11eb-8482-2ccaa9616357.png)

Independent Titles:
![Independent_Titles](https://user-images.githubusercontent.com/55886300/114741260-946ed700-9d18-11eb-899a-edb70d3c94a6.png)

And Empty Provinces (i.e., wasn't able to pull information from WtWSMS counties):
![empty_history](https://user-images.githubusercontent.com/55886300/114741292-9d5fa880-9d18-11eb-8c4a-8267d0a4cc01.png)

Red is no data, Orange are places I need to review again, and yellow are regions I think should be represented by independent counties instead of larger amalgamations. I'll note I added Acanne and Sarapion in Somalia from _Periplus of the Erythraean Sea_.

**Comment by loup99** [comment]
> So this is my proposal in the code for Roman Kingdoms:
> e_rome_kingdoms

So I don't agree with that proposal, I think the new kingdoms are unbalanced and will break the whole history we have. I think the kingdom map should be ported without any changes.

> ![image](https://user-images.githubusercontent.com/7620180/114763016-a6756780-9d62-11eb-9991-701fcc4c6d4a.png)

Same as for the kingdoms, many of those duchies are far too large, so I would port without changes.

> This aligns it with the 395 imperial reorganization by Diocleatian. The general gist is kingdom = diocese and duchy = province. I presume the Hispanic diocese is too large and should be subdivided so that the provinces become kingdoms instead, along with breaking up Roman Africa into the kingdoms of Maghreb, Africa, and Tripoltania?

Again, I'm sorry but I have to insist that Diocletian was long dead by 395. 395 is the division between East and West. You are referring to Tetrarchy of 293 when you are citing Diocletian. This might seem like a detail or me bickering due to my education in history at university, but there are differences between 395 and 293 in terms of institutions and administration. We even retained post-395 changes for the Imperial Reconquest (Illyricum). But yes on your remars with regards to Hispania and Africa, although I insist I think the CK2 setup should be retained.

> As an aside, we (should) be able to manipulate the can_create conditions to prevent non-Subroman/bureaucratic governments from creating these roman titles and instead giving them the option of "shattering" the Roman Administraiton and replacing it with new, smaller duchies that match the CK3 de jure setup. That'd make it possible to support both the Roman province system while still allowing for the general degradation of Roman governance that comes with the barbarian invasions.

I don't think dynamic de jure should be a priority as of now, but yes, something to keep in store for the future.

**Comment by loup99** [comment]
> And Empty Provinces (i.e., wasn't able to pull information from WtWSMS counties):

South of the Loire river it is the Visigoths, Corsica and Sardinia are under Vandal control, within Italy the WRE (vassals exist for the respective titles)

**Comment by LT-Rascek** [comment]
> So I don't agree with those changes from CK2, I think the new kingdoms are unbalanced and will break the whole history we have. I personally think the kingdom map should be ported without any changes.

>Same as for the kingdoms, many of those duchies are far too large, so I would port without changes.

Alright, I'll make these changes on #27 after pulling in the new landed title information. My only suggestion is to keep that data around so the history can be referenced in the future on dynamic de jure drift.

On the matter of the duchies; it depends on _which_ duchies you are referring. In Hispaniae I agree they are too large, but others like WTWSMS d_noricum, d_euregius, d_pannonia_superior, and d_andautonia would be overly large s well. To that end, I'll try to avoid importing overly large duchies from WTWSMS during this refactoring.

> Again, I'm sorry but I have to insist that Diocletian was long dead by 395. 395 is the division between East and West. You are referring to Tetrarchy of 293 when you are citing Diocletian. This might seem like a detail or me bickering due to my education in history at university, but there are differences between 395 and 293 in terms of institutions and administration. We even retained post-395 changes for the Imperial Reconquest (Illyricum). But yes on your remarks with regards to Hispania and Africa, although I insist I think the CK2 setup should be retained.

Alright, no problem; precision is key. I keep referencing 395 because its the associated date on [this map](https://en.wikipedia.org/wiki/Roman_province#/media/File:The_Roman_Empire_ca_400_AD.png) which I used to divide the dioceses/provinces, but you are correct about the changes between the Tetrarchy and the East/West division.

> Import since it was a setup we worked on extensively and which had seen community input.

Alright; I'll refactor based on Abian36's input.

> Having a kingdom centred around Altava isn't in opposition to several of the existing city states. As explained by Procopius that kingdom is a later phenomenon constructed progressively after 476. So it is after 476 that the polity centred around Altava managed to conquer other areas temporarily to reunify those territories. By the way, it is important that the Mauri aren't confused with the Romano-Berber polities.

Fair enough; I wanted to make certain we weren't overlooking things there.

> South of the Loire river and southern Lusitania it is the Visigoths, around the Seine Soissons, Corsica and Sardinia are under Vandal control, within Italy the WRE (vassals exist for most titles within the WRE) based upon the PLRE (Prosopography of the Later Roman Empire), central Anatolia, Greece and Thrace ERE (with PLRE vassals as well). The Orange ones in the Balkans should go to WRE in the West and Ostrogoths in the East.

I understand and could take initiative to fix it; given how I was moving ahead to implement things (since I have the time to do so), I figured I'd try to be circumspect in importing history for now, and will make not moving forward where I make decisions in absence of WTWSMS information.

**Comment by loup99** [comment]
> Alright, I'll make these changes on #27 after pulling in the new landed title information. My only suggestion is to keep that data around so the history can be referenced in the future on dynamic de jure drift.

Ok, no problems.

> On the matter of the duchies; it depends on which duchies you are referring. In Hispaniae I agree they are too large, but others like WTWSMS d_noricum, d_euregius, d_pannonia_superior, and d_andautonia would be overly large s well. To that end, I'll try to avoid importing overly large duchies from WTWSMS during this refactoring.

There are some WtWSMS duchies which are indeed too large, but I was rather thinking about Histria et Venetia than those you cite. 

> Alright, no problem; precision is key. I keep referencing 395 because its the associated date on this map which I used to divide the dioceses/provinces, but you are correct about the changes between the Tetrarchy and the East/West division.

There is also this map if it helps you:

![romana395ad](https://user-images.githubusercontent.com/7620180/114820886-03ebd180-9dc0-11eb-9293-ac10ee5dd1c0.jpg)

> Fair enough; I wanted to make certain we weren't overlooking things there.

The history between 477-600 could be modified for later bookmarks.

> I understand and could take initiative to fix it; given how I was moving ahead to implement things (since I have the time to do so), I figured I'd try to be circumspect in importing history for now, and will make note moving forward where I make decisions in absence of WTWSMS information.

No worries, I guess my reply wasn't the most detailed either, I could give you the exact vassals and rulers.

**Comment by LT-Rascek** [comment]
> There is also this map if it helps you:

Thanks, I'll cross-reference it.

> There are some WtWSMS duchies which are indeed too large, but I was rather thinking about Histria et Venetia than those you cite.

In CK3, county density in the HRE (in particular) is _much_ higher than from CK2, so most duchies in that region are probably too large.
E.g., Noricum and Pannonia Superior together would be over 20 counties (instead of 5 total in WtWSMS), Euregius would be about 12+ depending on how you split Tirol (4 in WtWSMS), Raetia-Curiensis is about 7 (4 in WtWSMS).

What's the ideal duchy size for this mod? 6-7 counties seems to make _most_ of the WtWSMS duchies map without being overly large.

Other titles I know will be an issue:
e_germania will be a big issue in general, so if you have some idea in mind on how to handle it, I'd like to hear it. I was mostly following CK3 vanilla with some additional changes closer to Roman territory (since Roman provinces distorted the situation there). Since there's only a few non-barony vassals, dealing with those regions isn't too bad so long as vanilla duchies are acceptable.

In North Africa (particularly south of the Roman controlled lands), the problem is the opposite; there's far fewer provinces and some things are very different (k_hodna and k_neumenchia should be near where k_sicca_veneria is instead of near the modern Moroccan border). 

In particular, the Garamentes subgroups are often reduced to one-province counties and some locations I am not able to find on maps I use, modern or older, or other sources. Some I do find, like Murzuk and Garama, but most I can't; either I'm getting the Romanization incorrect or you have sources for this that I can't find. Guidance there would be most helpful.

> No worries, I guess my reply wasn't the most detailed either, I could give you the exact vassals and rulers.

If you're fine with me making some estimates (example:  comparing known WtWSMS locations on Google Maps to see who owns this province that doesn't exist in WtWSMS), I can do that on my own. I'll mark them in the province map for future reference.

**Comment by loup99** [comment]
> In CK3, county density in the HRE (in particular) is much higher than from CK2, so most duchies in that region are probably too large.

Sure, the extra-Roman Germania areas are easier to split up there.

> E.g., Noricum and Pannonia Superior together would be over 20 counties (instead of 5 total in WtWSMS), Euregius would be about 12+ depending on how you split Tirol (4 in WtWSMS), Raetia-Curiensis is about 7 (4 in WtWSMS).

Those are difficult to split, we can't use the vanilla setup in those areas. Noricum is easy to split between Ripense and Mediterraneum. 

> Other titles I know will be an issue:
> e_germania will be a big issue in general, so if you have some idea in mind on how to handle it, I'd like to hear it. I was mostly following CK3 vanilla with some additional changes closer to Roman territory (since Roman provinces distorted the situation there). Since there's only a few non-barony vassals, dealing with those regions isn't too bad so long as vanilla duchies are acceptable.

The vanilla names do not make sense for our period, so what we did was a mix of Roman, geographic (Elbe, Vistula)
and political names (reflecting who controls the area). Would you be fine with using that as a base but sub-dividing existing duchies? Because I think the names and borders we have make more sense than going back to vanilla HRE stem duchies.

![ck2_68](https://user-images.githubusercontent.com/7620180/114976312-0a448100-9e86-11eb-9fc3-8e8dcf08f7e7.png)
 
> In North Africa (particularly south of the Roman controlled lands), the problem is the opposite; there's far fewer provinces and some things are very different (example: k_hodna and k_neumenchia should be near where k_sicca_veneria is instead of near the modern Moroccan border).

Those kingdoms shouldn't be de jure, I think the existing de jure kingdoms can be kept. The non-Roman areas shouldn't pose much of a problem, there we can merge our existing duchies from CK2.

> In particular, the Garamentes subgroups are often reduced to one-province counties and some locations I am not able to find on maps I use, modern or older, or other sources. Some I do find, like Murzuk and Garama, but most I can't; either I'm getting the Romanization incorrect or you have sources for this that I can't find. Others like Nasamoni are a single province or don't exist at all (Makrane, Berdoa). Guidance there would be most helpful.

The major cities are important, you already mention them. My opinion is that if the rest gets removed it is not a big issue for now in the initial port, so I would say don't spend too much time researching the area. If we decide we add provinces later on, we have the material from CK2, but otherwise it is fine. Therefore I would give you _carte blanche_ to redraw duchies based upon the major cities you found, like Murzuk and Garama.

> e_arabia has some very large desert blocks that greatly reduce d_yamama and quaryat dhat-kahil, and shrinks the Lakhmids and Ghassanids (to a lesser extent)

Qaryat Dhāt Kāhil would be the strongest candidate for removal if any duchy is to disappear.

> If you're fine with me making some estimates (example: comparing known WtWSMS locations on Google Maps to see who owns this province that doesn't exist in WtWSMS in either county or barony form), I can do that on my own.
> 
> I'll mark my deviations from WtWSMS on a map like this for future reference if that's fine.

Ok, perfect.

> Should past Roman Emperors Theodosius who hold both the WRE and Byzantium in WtWSMS hold e_roman_empire instead? It's a minor change that really only impacts history instead of gameplay, but I think it's worth considering.

For now let us not touch the 395 history, another mod team working on that start date offered to merge the two projects. I think the issue on this matter is that the past Roman Emperors need to be visible in WRE and ERE title history.

**Comment by LT-Rascek** [comment]
Closing as has been overtaken by other branches.
