### ISSUE TITLE
Innovations Notes

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#5]
Since it was brought up here: [https://forum.paradoxplaza.com/forum/threads/wip-a-migrational-era-mod-for-ck3.1414709/page-5#post-26933330](url), I have a few notes on innovations. I was holding off on posting this until the code base was more developed, but now seems as good a time as any.

General notes:
Innovations in base CK3 are closely tied to both government and culture, so they'll really should be modified more-or-less simultaneously; at least, that's my take on it.

General notion is to break up what would be the Vanila "Tribal Era" into the following groups, with some notable innovations listed (more details in the spreadsheet):

**Tribal Era (AD 1):**
* 10 Maximum Development
* Writing: Adopt High Tribal Government
* Migratory Warfare: Migration Casus Belli

**Late Antiquity (AD 200):**
* 20 Maximum Development
* Foederati: Level 3 High Tribal Authority, Foederati Special Contract (has to be a feudal contract of some sort since we can't have tributaries right now)
* State Religion: County Holy War, Send Missionaries Decisions (event-decision to allow for spreading religion in absence of court Chaplin mission)
* Coloniae: +15% Promote Culture Councilor Task Speed (Roman Culture)

**Migration Era (AD 450):**
* 25 Maximum Development
* Doctrine and Dogma: Religious Reformation (This would mean that Tribals couldn't do faith reformation, but high Tribals could; it's a change I thought made more sense), Religious Councils (when that decision gets coded)
* Legal Codex: Reconquer Rome Casus Belli (Latin & Byzantine Cultures)

**Rise of Islam (AD 700):**
* 30 Maximum Development
* Casus Belli: Enables De Jure Casus Belli
* Scriptural Canon: Duchy Holy War
* Themata: Themata Contract (Roman/Byzantine cultures) [useful for modeling the evolution of Themata in response to the Rise of Islam]
* Decentralization: Convert to Feudalism for High Tribals
* Kinship Records: Convert to Clan for High Tribals

**Early Middle Ages (AD 900):**
As seen in vanilla and so on

Most of the innovations are just one-line descriptions at this time, along with a few notes on holding changes (more steps leading to Mottes for example) and government details. The items listed in Blue in the spreadsheet should be worked out in more detail before implementation (Imperial Elective Succession, Adopt High Tribal Government, Send Missionaries Decision, Foederati Contract, Religious Councils).

Tribals would be locked into just Tribal Era innovations, High Tribals would be locked into before the Early Middle Ages. Given overall lower development in this mod, the a lower tech spread rate should keep the 250 year gaps between Tribal-Late Antiquity-Rise of Islam reasonable. The techs listed in the attached spreadsheet mostly would be combined with some changes to the default values so that most values converge to default CK3 values (levy reinforcement, taxation, etc) by AD 900.

I think you might want to reach out to Markellus of Rhomaioi mod or Knuckey333 or the Imperial Government mod to see if they'll let us implement some of their government modifications for the Bureaucratic government. I imagine it'd be useful for modeling Bureaucracy and Sub-Roman governments and save us some headache.

Other thoughts:
Considering breaking the Tribal Era in two if Tribals develop too quickly under this layout.

[innovations.xlsx](https://github.com/loup99/BP/files/5258652/innovations.xlsx)

**Comment by loup99** [comment]
Thank you for taking the time to do this. I generally agree with most of what you suggest, although some specific remarks.

> Migration Era (AD 450):

Could this enable a Migration CB, perhaps? Rise of Islam or Early Middle Ages could disable it.

> Religious Councils (when that decision gets coded)

From a historical point of view this isn't accurate since church councils happened before that, maybe the term could get reworded or reconsidered, although on the idea it could work.

> I think you might want to reach out to Markellus of Rhomaioi mod or Knuckey333 or the Imperial Government mod to see if they'll let us implement some of their government modifications for the Bureaucratic government. I imagine it'd be useful for modeling Bureaucracy and Sub-Roman governments and save us some headache.

Indeed, I was unsure on which one of the two to ask, although since Knuckey333 has a more generic imperial government it could be helpful for Eranshahr, I thought that might be more pertinent.

**Comment by LT-Rascek** [comment]
> Could this enable a Migration CB, perhaps? Rise of Islam or Early Middle Ages could disable it.

It couldn't if we're going to keep Migration CBs tribal, as we probably don't want to let tribal governments advance beyond the Tribal Era. An alternative would be to split the Tribal Era in two and have the migration CB in the second. Something like "Tribal Era" and "Iron Era". Either way, should be able to year-lock Migration CBs.

> From a historical point of view this isn't accurate since church councils happened before that, maybe the term could get reworded or reconsidered, although on the idea it could work.

Could put religious councils under "Late Antiquity/State Religion" and "Send Missionaries" under "Migration Era/Doctrine and Dogma" instead.

> Indeed, I was unsure on which one of the two to ask, although since Knuckey333 has a more generic imperial government it could be helpful for Eranshahr, I thought that might be more pertinent.

Aight, let me know whichever you decide and their response. I can start an overhaul of innovations/governments when that's been settled.

**Comment by loup99** [comment]
> It couldn't if we're going to keep Migration CBs tribal, as we probably don't want to let tribal governments advance beyond the Tribal Era. An alternative would be to split the Tribal Era in two and have the migration CB in the second. Something like "Tribal Era" and "Iron Era". Either way, should be able to year-lock Migration CBs.

In that case it will have to remain being tied to government and have the year lock, or have it be tied to some event to be a bit more flexible.

> Could put religious councils under "Late Antiquity/State Religion" and "Send Missionaries" under "Migration Era/Doctrine and Dogma" instead.

Sounds like a good solution.

> Aight, let me know whichever you decide and their response. I can start an overhaul of innovations/governments when that's been settled.

I'm going to get in touch with Knuckey333 in that case.

**Comment by loup99** [comment]
We have received a positive response from knuckey, for your information

**Comment by LT-Rascek** [comment]
Alright, then I'll look into his implementation and see what I can take from it. Need to review the previous work done on innovations as well.

**Comment by LT-Rascek** [comment]
#18 Will complete this, so closing.
