### ISSUE TITLE
Complete Alpha Tasks

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#59]
### Character History
- [x] Add BM476 Foederati, Tributary for those powers with such relationships:
   * ERE: Thracian Goths (Foederati), Lazica (Tributary), Sarir (Tributary), Ghassanids (Foederati)
   * Persia: Iberia (Tributary), Caucasian Albania (Tributary), Lakhmids (Tributary), Bukhara (Tributary), Khwarezem (Tributary)
   * Hephthalites (all Tributaries): Khuttal, Samarkand, Chach, Oshrusana, Fergana, Dahae, Zunbils, Kashgar
- [x] Fix some platonists having dead friends (i.e., char is dead when friendship assigned)
- [x] Assassination of Iulius Nepos:  send_assassin is invalid in CK3
   * Implemented as Ovida murdering him on his death day
- [x] Reimplement character events if desired
   * vandalic.txt
- [x] Parse out special chars for certain special titles (e.g., e_palmyra,e_selecuid) to better clarify character history
- [x] Handle potential duplicate character cases:
   * nepali.txt (Licchaivi dynasty might have some)

### Vanilla Features to Suppress
- [x] Overhaul heresy events to avoid ahistorical religions
- [x] Overhaul character spawns to avoid ahistorical religions

### New Features
- [x] Fix independent gubernatorial_government upon independence; try to trigger "when landed" conditions to have can_get_government to be used instead of other code.
- [x] Non-bureaucratic lieges of gubernatorials should change government to subroman

### Dynasties
- [x] Review if any dynasties should be converted to houses instead
   * Gupta probably, some others in India probably
   * ~~Arascids in Caucasia~~

### UI
- [x] Overhaul event widgets to support scrolling options for hellenic patron deity mechanic.
- [ ] Tweak Faith Gui to support sin/virtue scrolling
- [x] Fix hair bug for Childeric/Gundobad DNA

### Localizations
- [x] Localization for new Buddhist religions

## Gameplay Errors
- [x] Fix creation of feudal/clan governments being created when granting or succeeding titles (H/T @Abian36 )
- [x] Potential CTD involved with some characters dying (namely patriarch of Jerusalem, Antioch)
- [x] Refactor title_on_actions to suppress "trying to set illegal government" errors.

## Final steps before prepping for review
- [x] Standardize all (regex) "#+ Change[d*] from Vanilla" type strings
- [x] Bring all other code up to philosophy standard

## Need feedback
* Revamp c_constantinople to support new baronies
   * Probably not needed for Alpha

## Probably not fixable
(or at least not simple)
* Probably need to remove and rewrite pentarchs wholesale
- [x] Fix non-HOF theocracy religious titles being inheritable or revocable by secular rulers (H/T Abian36 )
  * Demanding conversion of Ecumenical Patriarch and Patriarchy of Antioch changes the inheritance laws.
- [x] Prevent baronies owned by religious dukes from reverting to county holders if possible.
- [x] Fix women being able to inherit male-only titles in the 476 start
   * Seems to be an issue in Vanilla as well (see comment below)
- [x] Figure out how to workout "impregnate" effect in illyro_roman.txt
   * Can't specify pregnancy state in char history as of v1.4.4, can only add trait

**Comment by kai229** [comment]
Ran a couple of observer games. Here are the two most notable bugs:

1. Odoacer's daughter succeeded him as Queen of Italy (the title has male only law).
2. The Kingdom of Italy and Ostrogothica do not show the _Primary Heir_ box which is usually seen.

**Comment by LT-Rascek** [comment]
Reviewing the "Female successors at start" this seems to be a much deeper issue as I've seen this occur in Vanilla as well.

Example from a Vanilla, mod-less 1066 game I tested, a few days after letting the game run (Salic-law France).

![20220115025226_1](https://user-images.githubusercontent.com/55886300/149634781-26828c4d-0a07-431d-b5ba-046f7c6e57ba.jpg)

I recommend shelving fixing this bug and reviewing Bug Reports (BR) to PDX. If no extant BRs cover this issue, then I will make one and send it to them.

**Comment by LT-Rascek** [comment]
Still has several linked issues connected.

**Comment by Majdian** [comment]
Hi der
I'm node mining many how can meike many?
