### ISSUE TITLE
Culture of Cyrenaica

### ISSUE THREAD

**Issue by Symmachus** [loup99/BP#79]
I don't think that Cyrenaica should be Coptic. Linguistic maps of the Byzantine Empire under Justinian list this area under "Greek and Native", where Native probably mean Berber, since Coptic is listed under its own category. That makes more sense, because Cyrenaica was colonized by the Greeks and their colonies formed local Pentapolis. So, I would suggest to change Cyrenaica's culture to Greek or add a new culture called Libyco-Greek. This culture for late-antiquity Cyrenaica was created by Asakhra, who also made several cultures already used in the mod.

Here is the link for Asakhra's Libyco-Greek culture, with unique namelists: https://forum.paradoxplaza.com/forum/threads/new-cultures.610605/page-40#post-19562981

**Comment by LT-Rascek** [comment]
The Pentapolis is current Greek culture in CK3. I'll create and replace the region with Libyo-Greek.
