### ISSUE TITLE
Erik W's bloodlines

### ISSUE THREAD

**Issue by Symmachus** [loup99/BP#80]
@LT-Rascek, you correctly noted that some characters like Varus the Younger and Avidius Cassius didn't historically belonged to Octavianus dynasty. But that's actually how Erik set things up, continuing various famous bloodlines through female lines. For example, later members of "S. J. Caesar" dynasty considered themselves to be Sextii, Vettii, Caecinii etc, but not "Caesarians". What should we do with them? I can add husbands and stuff, moving characters to their appropriate families, but it will take a lot of work.

**Comment by LT-Rascek** [comment]
I'd say that's the best solution; for many I found they have husbands listed. It's a nice-to-do, not a have-to-do though. I noticed the various inaccuracies when I was implementing the full Seleucid history.

I've listed fixing up the Julio-Claudian family tree as something that falls under Beta, so there's no rush to fix it.

**Comment by loup99** [comment]
Agreed, with the new bloodline and ancestry mechanics matrilineal dynastic continuity should probably be removed, but as @LT-Rascek  suggests it is not the top priority at the moment.

**Comment by Symmachus** [comment]
I've fixed everything in my PR, so this issue is no longer relevant.
